#                 Generated by Gemini
#                 20260106 - first release
#Requires         -Version 7.1
$DisklogFile = "disk.log"
$targetFolderList = @("\\172.22.111.5\RD-share\Japan-office\MUL-799909\10 DHIO\disk5001_to_disk5010",
  "\\172.27.112.171\Log\Performance\tokyo\0611\0102_seqread_8_1",
  "\\172.27.112.171\Log\Performance\tokyo\0612\0102_seqread_8_1",
  "\\172.27.112.171\Log\Performance\tokyo\0616\0102_seqread_8_1",
  "\\172.27.112.171\Log\Performance\tokyo\0618\0102_seqread_8_1_fail0106",
  "\\172.27.112.171\Log\Performance\tokyo\0618\0102_seqread_8_1_fail0106_slot2_1"
)

$fileNamePattern = "*.a.3"           # 檔名關鍵字： 例如 "report*" 或 "*" (找全部)
# [0-9A-F]{3} 代表前3碼為十六進位
# \s+          代表中間有空格
# [0-9A-F]{2} 代表中間1 or 2碼為十六進位
# /            代表斜線
# \d{2}        代表最後2碼為純數字 (等同於 [0-9]{2})
$diskPattern = '^[0-9A-F]{3}\s+[0-9A-F]{1,2}/\d{2}'

#_PD_   Slot_LD    R_MB/s__IO/s___ms/io____max  W_MB/s__IO/s___ms/io____max   _seek___(max)  idle qd S% B%
#000 FF/01 00     1.2     3      1.81    2.3     0.0     0    0.00    0.0    1.31    1.62  997   1
# Index
$PD = 0
$SLOT = 1
$LD = 2
$RMBs = 3
$RIOs = 4
$Rmsio = 5
$Rmax = 6
$WMBs = 7
$WIOs = 8
$Wmsio = 9
$Wmax = 10
$Seek = 11
$SeekMax = 12
$Idle = 13
$QD = 14


# Compare rule
$LongReadLatency = 90
$LongWriteLatency = 0
$numOfMatched = 0
$numOfMatchedInSystem = 0

# Main function starts

$logList = New-Object System.Collections.Generic.List[string]

foreach ($folder in $targetFolderList) {
  $results = Get-ChildItem -Path $folder -Filter $fileNamePattern -Recurse -ErrorAction SilentlyContinue |
  Where-Object {
    !$_.PSIsContainer -and
    $_.Length -ge 0
  } |
  Select-Object -ExpandProperty FullName

  $numOfMatchedInSystem = 0
  foreach ($dhioFile in $results) {
    Write-Host "$($dhioFile)"
    $matchesDisk = Select-String -Path $dhioFile -Pattern $diskPattern

    # 輸出找到的結果
    foreach ($match in $matchesDisk) {
      $diskBlocks = $match.Line -split '\s+'
      # JBOD and slot number
      #$diskSlot = $diskBlocks[$SLOT] -split '/'
      # diskSlot[0] - JBOD, 0 or FF is RAID, others are JBOD ID
      # diskSlot[1] - slot number
      # Get Long latency
      if (([float]$diskBlocks[$Rmax] -ge $LongReadLatency) -or ($LongWriteLatency -ne 0 -and [float]$diskBlocks[$Wmax] -ge $LongWriteLatency)) {
        if ($numOfMatchedInSystem -eq 0) {
          $logList.Add($dhioFile)
          $logList.Add("_PD_Slot_LD  R_MB/s__IO/s___ms/io____max  W_MB/s__IO/s___ms/io____max   _seek___(max)  idle qd S% B%")
        }
        $logList.Add($match.Line)
        Write-Host "$($match.Line)"
        $numOfMatched++
        $numOfMatchedInSystem++
      }
    }
  }


}
if ($numOfMatched -gt 0) {
  $logList | Out-File -FilePath $DisklogFile -Encoding utf8
}
